# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `dry-swagger` gem.
# Please instead update this file by running `bin/tapioca gem dry-swagger`.


# source://dry-swagger//lib/dry/swagger/documentation_generator.rb#1
module Dry
  class << self
    # source://dry-configurable/1.3.0/lib/dry/configurable.rb#11
    def Configurable(**options); end

    # source://dry-core/1.1.0/lib/dry/core.rb#52
    def Equalizer(*keys, **options); end

    # source://dry-struct/1.8.0/lib/dry/struct.rb#30
    def Struct(attributes = T.unsafe(nil), &block); end

    # source://dry-types/1.8.2/lib/dry/types.rb#253
    def Types(*namespaces, default: T.unsafe(nil), **aliases); end
  end
end

# source://dry-swagger//lib/dry/swagger/documentation_generator.rb#2
module Dry::Swagger; end

# source://dry-swagger//lib/dry/swagger/config/configuration.rb#3
module Dry::Swagger::Config; end

# source://dry-swagger//lib/dry/swagger/config/configuration.rb#4
module Dry::Swagger::Config::Configuration
  # @yield [_self]
  # @yieldparam _self [Dry::Swagger::Config::Configuration] the object that the method was called on
  #
  # source://dry-swagger//lib/dry/swagger/config/configuration.rb#5
  def configuration; end

  # source://dry-swagger//lib/dry/swagger/config/configuration.rb#9
  def define_setting(name, default = T.unsafe(nil)); end

  private

  # source://dry-swagger//lib/dry/swagger/config/configuration.rb#23
  def define_class_method(name, &block); end
end

# source://dry-swagger//lib/dry/swagger/config/swagger_configuration.rb#4
module Dry::Swagger::Config::SwaggerConfiguration
  extend ::Dry::Swagger::Config::Configuration

  class << self
    # source://dry-swagger//lib/dry/swagger/config/configuration.rb#16
    def enable_descriptions; end

    # source://dry-swagger//lib/dry/swagger/config/configuration.rb#12
    def enable_descriptions=(value); end

    # source://dry-swagger//lib/dry/swagger/config/configuration.rb#16
    def enable_enums; end

    # source://dry-swagger//lib/dry/swagger/config/configuration.rb#12
    def enable_enums=(value); end

    # source://dry-swagger//lib/dry/swagger/config/configuration.rb#16
    def enable_nullable_validation; end

    # source://dry-swagger//lib/dry/swagger/config/configuration.rb#12
    def enable_nullable_validation=(value); end

    # source://dry-swagger//lib/dry/swagger/config/configuration.rb#16
    def enable_required_validation; end

    # source://dry-swagger//lib/dry/swagger/config/configuration.rb#12
    def enable_required_validation=(value); end

    # source://dry-swagger//lib/dry/swagger/config/configuration.rb#16
    def nullable_type; end

    # source://dry-swagger//lib/dry/swagger/config/configuration.rb#12
    def nullable_type=(value); end
  end
end

# source://dry-swagger//lib/dry/swagger/documentation_generator.rb#3
class Dry::Swagger::DocumentationGenerator
  # @return [DocumentationGenerator] a new instance of DocumentationGenerator
  #
  # source://dry-swagger//lib/dry/swagger/documentation_generator.rb#16
  def initialize; end

  # @return [Boolean]
  #
  # source://dry-swagger//lib/dry/swagger/documentation_generator.rb#111
  def array_of_primitive_type?(definition); end

  # source://dry-swagger//lib/dry/swagger/documentation_generator.rb#20
  def from_struct(struct); end

  # source://dry-swagger//lib/dry/swagger/documentation_generator.rb#24
  def from_validation(validation); end

  # source://dry-swagger//lib/dry/swagger/documentation_generator.rb#28
  def generate_documentation(fields); end

  # source://dry-swagger//lib/dry/swagger/documentation_generator.rb#47
  def generate_field_properties(definition); end

  # source://dry-swagger//lib/dry/swagger/documentation_generator.rb#88
  def generate_for_array(definition); end

  # @raise [Errors::MissingHashSchemaError]
  #
  # source://dry-swagger//lib/dry/swagger/documentation_generator.rb#98
  def generate_for_hash(definition); end

  # source://dry-swagger//lib/dry/swagger/documentation_generator.rb#103
  def generate_for_primitive_type(definition); end

  # source://dry-swagger//lib/dry/swagger/documentation_generator.rb#65
  def generate_for_sti_type(definition); end
end

# source://dry-swagger//lib/dry/swagger/documentation_generator.rb#4
Dry::Swagger::DocumentationGenerator::SWAGGER_FIELD_TYPE_DEFINITIONS = T.let(T.unsafe(nil), Hash)

# source://dry-swagger//lib/dry/swagger/errors/missing_hash_schema_error.rb#3
module Dry::Swagger::Errors; end

# source://dry-swagger//lib/dry/swagger/errors/missing_hash_schema_error.rb#4
class Dry::Swagger::Errors::MissingHashSchemaError < ::StandardError
  # source://dry-swagger//lib/dry/swagger/errors/missing_hash_schema_error.rb#5
  def message; end
end

# source://dry-swagger//lib/dry/swagger/errors/missing_type_error.rb#4
class Dry::Swagger::Errors::MissingTypeError < ::StandardError
  # source://dry-swagger//lib/dry/swagger/errors/missing_type_error.rb#5
  def message; end
end

# source://dry-swagger//lib/dry/swagger/version.rb#3
Dry::Swagger::VERSION = T.let(T.unsafe(nil), String)
