# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `dry_validation_parser` gem.
# Please instead update this file by running `bin/tapioca gem dry_validation_parser`.


# source://dry_validation_parser//lib/dry_validation_parser/validation_schema_parser.rb#3
module DryValidationParser; end

# source://dry_validation_parser//lib/dry_validation_parser/validation_schema_parser.rb#4
class DryValidationParser::ValidationSchemaParser
  # @api private
  # @return [ValidationSchemaParser] a new instance of ValidationSchemaParser
  #
  # source://dry_validation_parser//lib/dry_validation_parser/validation_schema_parser.rb#38
  def initialize; end

  # @api private
  #
  # source://dry_validation_parser//lib/dry_validation_parser/validation_schema_parser.rb#48
  def call(contract, &block); end

  # @api private
  #
  # source://dry_validation_parser//lib/dry_validation_parser/validation_schema_parser.rb#35
  def keys; end

  # source://dry_validation_parser//lib/dry_validation_parser/validation_schema_parser.rb#138
  def predicate_description(name, value); end

  # @api private
  #
  # source://dry_validation_parser//lib/dry_validation_parser/validation_schema_parser.rb#43
  def to_h; end

  # @api private
  #
  # source://dry_validation_parser//lib/dry_validation_parser/validation_schema_parser.rb#56
  def visit(node, opts = T.unsafe(nil)); end

  # @api private
  #
  # source://dry_validation_parser//lib/dry_validation_parser/validation_schema_parser.rb#80
  def visit_and(node, opts = T.unsafe(nil)); end

  # @api private
  #
  # source://dry_validation_parser//lib/dry_validation_parser/validation_schema_parser.rb#103
  def visit_each(node, opts = T.unsafe(nil)); end

  # @api private
  #
  # source://dry_validation_parser//lib/dry_validation_parser/validation_schema_parser.rb#95
  def visit_implication(node, opts = T.unsafe(nil)); end

  # @api private
  #
  # source://dry_validation_parser//lib/dry_validation_parser/validation_schema_parser.rb#108
  def visit_key(node, opts = T.unsafe(nil)); end

  # source://dry_validation_parser//lib/dry_validation_parser/validation_schema_parser.rb#61
  def visit_namespace(node, opts = T.unsafe(nil)); end

  # source://dry_validation_parser//lib/dry_validation_parser/validation_schema_parser.rb#90
  def visit_not(_node, opts = T.unsafe(nil)); end

  # Skip or predicate
  #
  # source://dry_validation_parser//lib/dry_validation_parser/validation_schema_parser.rb#88
  def visit_or(_, _); end

  # @api private
  #
  # source://dry_validation_parser//lib/dry_validation_parser/validation_schema_parser.rb#116
  def visit_predicate(node, opts = T.unsafe(nil)); end

  # @api private
  #
  # source://dry_validation_parser//lib/dry_validation_parser/validation_schema_parser.rb#66
  def visit_set(node, opts = T.unsafe(nil)); end
end

# source://dry_validation_parser//lib/dry_validation_parser/validation_schema_parser.rb#24
DryValidationParser::ValidationSchemaParser::DESCRIPTION_MAPPING = T.let(T.unsafe(nil), Hash)

# source://dry_validation_parser//lib/dry_validation_parser/validation_schema_parser.rb#5
DryValidationParser::ValidationSchemaParser::PREDICATE_TO_TYPE = T.let(T.unsafe(nil), Hash)
